<h4><b>NUMPY = Numerical Python</b></h4>
It is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

In [62]:
#29th July
import numpy as np
np.__version__

'2.0.1'

<h4><b>Creating an array    [1D]</b></h4>

In [66]:
arr=np.array([25,10,20,30,40,50,60])        #creating and displaying an 1D array
arr

array([25, 10, 20, 30, 40, 50, 60])

In [65]:
ls=[25,10,20,30,40,50,60]       #converting list into an array
arr=np.array(ls)
arr

array([25, 10, 20, 30, 40, 50, 60])

In [31]:
print(arr)

[25 10 20 30 40 50 60]


In [32]:
type(ls)

list

In [33]:
type(arr)

numpy.ndarray

<h4><b>Basic functions in Numpy</b></h4>

In [10]:
arr+5       #added 5 to every element of the array

array([30, 15, 25, 35, 45, 55, 65])

In [11]:
arr / 5

array([ 5.,  2.,  4.,  6.,  8., 10., 12.])

In [12]:
max(arr)        #max() function returns the maximum element in the array

np.int64(60)

In [13]:
min(arr)        #min() function returns the minimum element in the array

np.int64(10)

In [69]:
np.sort(arr)        #sort() function sorts the array elements by default in ascending order

array([10, 20, 25, 30, 40, 50, 60])

In [14]:
sum(arr)        #returns the sum of all elements in the array

np.int64(235)

In [15]:
np.mean(arr)        #returns the avg/mean of array elements

np.float64(33.57142857142857)

In [16]:
np.median(arr)      #returns the median(mid element) in the array

np.float64(30.0)

In [91]:
np.mode(arr)        #Numpy has no MODE Function

AttributeError: module 'numpy' has no attribute 'mode'

In [98]:
np.std(arr)     #returns standard deviation

np.float64(2.581988897471611)

*<b>(ndarray</b>= n-dimensional array)*

In [4]:
arr.ndim        #returns dimension of array

1

In [5]:
arr.size        #or     len(arr)        #tells the size of the array(no. of elements)

7

In [6]:
arr.shape       #returns a tuple indicating dimension of an object

(7,)

In [37]:
arr.dtype       #returns data type of array(type of elements stored in array)

dtype('int64')

In [38]:
arr=np.array([25,10,20,30,'Hello'])
arr

array(['25', '10', '20', '30', 'Hello'], dtype='<U21')

In [27]:
arr.dtype

dtype('<U21')

<h4><b>Slicing/Indexing in 1D Array</b></h4>

In [60]:
arr = np.array([25,10,20,40,40,50,60])      
arr[-3::1]      #or arr[-3:]      #last 1 is known as jump point and shows we have to move in forward direction and if it is negative then it shows that we have to move in backward direction

array([40, 50, 60])

<h4><b>Random Module</b></h4>

In [19]:
import random
random.randint(1,20)        #generate a number randomly between 1 and 20
#The output of this will be different everytime we run it cause the numbers are being generated randomly

18

In [28]:
arr=np.random.randint(1,10,5)        #it means generate 5 numbers randomly between 1 and 10
arr

array([4, 1, 9, 8, 3], dtype=int32)

In [30]:
arr=np.random.randint(1,10,5)
arr.dtype

dtype('int32')

In [31]:
arr=np.random.randint(1,10,5,dtype='int64')     #In the above case , the data type was coming out to be INT32 but here we have specified what data type we want accoring to our choice 
arr.dtype

dtype('int64')

In [37]:
#30th July
import numpy as np
arr=np.random.randint(1,20,30)        #it means generate 30 numbers randomly between 1 and 20
arr

array([ 8,  6, 11, 17, 15,  8,  1, 18, 12, 16,  7,  5, 17,  4, 18, 18,  3,
        5, 17, 14,  5,  8,  5, 15, 12, 14, 19, 13, 14,  2], dtype=int32)

In [39]:
arr<10     #returns TRUE where the condition is met and returns FALSE where it is not met

array([ True,  True, False, False, False,  True,  True, False, False,
       False,  True,  True, False,  True, False, False,  True,  True,
       False, False,  True,  True,  True, False, False, False, False,
       False, False,  True])

ALTERNATE METHOD

In [40]:
def lessthan10():               
    numbers=arr[arr<10]
    print(numbers)

lessthan10()

[8 6 8 1 7 5 4 3 5 5 8 5 2]


In [41]:
len(arr[arr<10])        #returns the no. of elements less than 10

13

<h4><b>String Module</b></h4>

In [42]:
import string
string.digits

'0123456789'

In [43]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [44]:
str=string.ascii_letters+string.digits
str.split()

['abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789']

<h4><b>2D Array</b></h4>

In [49]:
ls=[[1,2,3],[4,5,6],[7,8,9]]
ls

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [50]:
type(ls)

list

In [51]:
arr2=np.array(ls)
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
arr2.ndim

2

In [52]:
arr2.shape      #represents no. of rows and columns

(3, 3)

<h4><b>Slicing/Indexing in 2D Array</b></h4>

In [44]:
arr2[2]     

array([7, 8, 9])

In [53]:
arr2[-2]        

array([4, 5, 6])

In [54]:
arr2[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
arr2[0:2,1:3]      #row,column

array([[2, 3],
       [5, 6]])

In [56]:
arr2[1:3,0:2]

array([[4, 5],
       [7, 8]])

In [57]:
arr2[0:,1:3]

array([[2, 3],
       [5, 6],
       [8, 9]])

<h4><b>3D Array</b></h4>

In [72]:
ls1=[[[1,2],[3,4]],
     [[5,6],[7,8]],
     [[9,10],[11,12]]]
ls1

[[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]]

In [73]:
arr3=np.array(ls1)
arr3

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [13]:
arr3.ndim

3

In [74]:
arr3.shape      #table,row,column       
#It indicates that this arr3 array has 3 (2-D) arrays that have a shape of 2*2 which means that they have 2 rows and 2 columns

(3, 2, 2)

In [19]:
arr3[:,0,:]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [26]:
ls2=[[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]]
arr4=np.array(ls2)
arr4

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

<h4><b>Slicing/Indexing in 3D Array</b></h4>

In [31]:
arr4[:,1:,1:]

array([[[5, 6],
        [8, 9]],

       [[5, 6],
        [8, 9]],

       [[5, 6],
        [8, 9]],

       [[5, 6],
        [8, 9]]])

In [37]:
arr4[:,-1,::-1]

array([[9, 8, 7],
       [9, 8, 7],
       [9, 8, 7],
       [9, 8, 7]])

<h4><b>Advanced Functions in Numpy</b></h4>

1. RAVEL()

In [39]:
arr3.ravel()        #or flatten() function      #used to change a 2-dimensional array or a multi-dimensional array into a contiguous flattened array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

2. RESHAPE()

In [76]:
arr3.reshape(12,)       #shape=(3,2,2) = 3*2*2=12       #gives a new shape to an array without changing its data.

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

3. ARGMIN()

In [77]:
l=[5,2,8,6,1,9,3]
a=np.array(l)
a
np.argmin(a,axis=0)     #numpy.argmin(array, axis = None, out = None) = returns index of the min element of the array in a particular axis

np.int64(4)

4. ARGMAX()

In [78]:
np.argmax(a,axis=0)     #returns index of the max element of the array in a particular axis

np.int64(5)

5. ARGSORT()

In [79]:
np.argsort(a)      #numpy.argsort(arr, axis=-1, kind=’quicksort’, order=None)=returns an array of indices of value arranged in ascending order

array([4, 1, 6, 0, 3, 2, 5])

6. ONES()

In [58]:
np.ones(10)     #returns a new array of given shape and type, with ones

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

7. ZEROES()

In [59]:
np.zeros(5)     #returns a new array of given shape and type, with zeros

array([0., 0., 0., 0., 0.])

8. LINSPACE()

In [60]:
np.linspace(1,20,10)        #returns uniform distribution of 10 numbers between 1 and 20

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

9. POWER()

In [87]:
array1 = [2, 2, 2, 2, 2] 
array2 = [2, 3, 4, 5, 6]
out=np.power(array1,array2)     #array element from first array is raised to the power of element from second array
out

array([ 4,  8, 16, 32, 64])

10. SIGN()

In [89]:
ar1=[1,4,0,-3,0,-6]
ar2=np.sign(ar1)        #indicates the sign of a number element-wise. For integer inputs, if array value is greater than 0 it returns 1, if array value is less than 0 it returns -1, and if array value 0 it returns 0.
ar2

array([ 1,  1,  0, -1,  0, -1])

11. SUBTRACT()

In [92]:
ar1 = [2, 2, 2, 2, 2] 
ar2 = [2, 3, 4, 5, 6]
ar=np.subtract(ar2,ar1)     #subtracts two arrays element-wise
ar

array([0, 1, 2, 3, 4])

12. RECIPROCAL()

In [93]:
a=[0.5,1,0.25,0.2]
r=np.reciprocal(a)      #returns the reciprocal of array elements
r

array([2., 1., 4., 5.])

13. RESIZE()

In [97]:
gfg = np.array([1, 2, 3, 4, 5, 6])
gfg.resize(2,3)                     #resizes the array into our desired shape
gfg                                 #Here, converted a 1D array into 2D array of 2 rows and 3 columns

array([[1, 2, 3],
       [4, 5, 6]])

14. SAVETXT()

In [102]:
array1 = np.array([[1, 3, 5], 
                   [7, 9, 11]])
np.savetxt('file1.txt', array1)        #save an array to a text file

15. LOADTXT()

In [104]:
loaded_array = np.loadtxt('file1.txt')      #load the saved txt file
print(loaded_array)

[[ 1.  3.  5.]
 [ 7.  9. 11.]]


<h4><b>Some Practice Program</b></h4>

In [80]:
#Problem 1. Given a 1D Numpy array, replace all negative values with zero.
def replace(arr):
    arr[arr<0]=0
    return arr
arr=np.array([1,-2,3,5,-7,-9])
result=replace(arr)
print(result)

[1 0 3 5 0 0]


<h4><b>WHERE Function in Numpy</b></h4>
Syntax : numpy.where(condition[, x, y])<br>
condition : When True, yield x, otherwise yield y.

In [83]:
#Problem 2. Given a 1D Numpy array , return a new array where if element is greater than 5 then square it and if less thaan 5 then return 0.
def pract(arr):
    result=np.where(arr>=5,arr**2,0)
    return result
arr=np.array([1,3,5,6,8,2,9,4])
result=pract(arr)
print(result)

[ 0  0 25 36 64  0 81  0]


In [85]:
#Problem 3. Given a 2D Array , return sum of each row as a 1D Array.
def row_sum(data):
    return np.sum(data,axis=1)
data=np.array([[1,2,3],[4,5,6],[7,8,9]])
r_sum=row_sum(data)
print(r_sum)

[ 6 15 24]


In [86]:
#Problem 4. Given a 2D Numpy Array, extract all even numbers
def even(arr):
    return arr[arr%2==0]
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
even_no=even(arr)
print(even_no)

[2 4 6 8]
